# Generated by Django 5.1.3 on 2024-11-06 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('room_type', models.CharField(choices=[('single', 'Single'), ('double', 'Double'), ('suite', 'Suite'), ('family', 'Family')], max_length=20)),
                ('bed_type', models.CharField(choices=[('single', 'Single'), ('double', 'Double'), ('queen', 'Queen'), ('king', 'King')], max_length=20)),
                ('floor', models.IntegerField()),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=10)),
                ('capacity_adults', models.IntegerField()),
                ('capacity_children', models.IntegerField()),
                ('has_wifi', models.BooleanField(default=True)),
                ('has_ac', models.BooleanField(default=True)),
                ('has_heating', models.BooleanField(default=True)),
                ('has_tv', models.BooleanField(default=True)),
                ('has_bathroom', models.BooleanField(default=True)),
                ('has_bathtub', models.BooleanField(default=False)),
                ('has_shower', models.BooleanField(default=True)),
                ('has_minibar', models.BooleanField(default=False)),
                ('has_safe', models.BooleanField(default=False)),
                ('has_desk', models.BooleanField(default=True)),
                ('has_wardrobe', models.BooleanField(default=True)),
                ('has_coffee_maker', models.BooleanField(default=False)),
                ('has_balcony', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='RoomImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='room_images/')),
                ('is_primary', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='rooms.room')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
