# Generated by Django 5.1.3 on 2024-11-07 16:58

import django.utils.timezone
import imagekit.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roomimage',
            options={'ordering': ['order', 'uploaded_at']},
        ),
        migrations.AddField(
            model_name='roomimage',
            name='caption',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='roomimage',
            name='image_format',
            field=models.CharField(choices=[('JPEG', 'JPEG'), ('PNG', 'PNG'), ('WebP', 'WebP'), ('GIF', 'GIF')], default='JPEG', max_length=10),
        ),
        migrations.AddField(
            model_name='roomimage',
            name='uploaded_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='roomimage',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(upload_to='room_images'),
        ),
    ]
