# Generated by Django 5.1.3 on 2024-11-08 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_alter_room_options_rename_has_shower_room_has_closet_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomimage',
            name='image_format',
        ),
        migrations.AddField(
            model_name='roomimage',
            name='format',
            field=models.CharField(choices=[('JPEG', 'JPEG'), ('PNG', 'PNG'), ('WEBP', 'WebP')], default='JPEG', help_text='Select the output format for this image', max_length=10),
        ),
        migrations.AlterField(
            model_name='roomimage',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
